### ISSUE TITLE
Use logging.debug instead of print in parser.py

### ISSUE THREAD

**Issue by firepol** [VerenigingCampusKabel/python-sepa#2]
Hi,

can you please get rid of the print statement in parser.py that prints "Unknown tag"?
It's kinda useless to see it all the time and pollutes the console.

In my repo/branch I fixed it myself and replaced it with logging.debug, see:
https://github.com/firepol/python-sepa/commit/17874e3ebdd5bef6634a833675085650847a3352

Maybe you want to clean up also other commented print statements I've seen around and also replace them with `logging.debug`: logging is convenient as you can leave all logging statements uncommented, and activate only the debug level when you really need to debug.

Thx again for fixing the previous issue and for considering this one, cheers

**Comment by DanielHuisman** [comment]
Thanks for reporting this issue. In the latest release I replaced all print statements with `logging.debug`.
